name: Get Github Revision Info
description: Get Github revision information

outputs:
  sha:
    value: ${{ steps.get-rev.outputs.sha }}
  branch:
    value: ${{ steps.get-rev.outputs.branch }}

runs:
  using: composite
  steps:
    - name: Get revision SHA and branch
      id: get-rev
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          if [ "${{ github.event.pull_request.merged }}" == true ]; then
            sha="${{ github.sha }}"
            branch="${{ github.base_ref }}"
            echo "PR merged. SHA: $sha, Branch: $branch"
          else
            sha="${{ github.event.pull_request.head.sha }}"
            branch="${{ github.event.pull_request.head.ref }}"
            echo "PR not yet merged. SHA: $sha, Branch: $branch"
          fi
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          sha="${{ github.sha }}"
          branch="${{ github.event.ref_name }}"
          echo "Workflow dispatch event. SHA: $sha, Branch: $branch"
        else
          echo "Event not supported."
          exit 1
        fi
        echo "sha=${sha}" >> "$GITHUB_OUTPUT"
        echo "branch=${branch}" >> "$GITHUB_OUTPUT"
      shell: bash
