name: Commit File
description: Commit file (signed)

inputs:
  branch:
    required: true
  file:
    required: true
  message:
    required: true
  repo:
    default: ${{ github.repository }}
  token:
    default: ${{ github.token }}
  workdir:
    default: '.'

runs:
  using: composite
  steps:
    - name: Verify file changed
      id: verify-file-changed
      working-directory: ${{ inputs.workdir }}
      run: |
        res=0
        git diff --quiet ${{ inputs.file }} || res="$?"
        [ "$res" != 0 ] && [ "$res" != 1 ] && exit "$((res + 0))"
        changed=$([ "$res" == 0 ] && echo 'false' || echo 'true')
        echo "changed=${changed}" >> "$GITHUB_OUTPUT"
        echo "changed=${changed}"
      shell: bash

    - name: Commit file
      if: ${{ steps.verify-file-changed.outputs.changed == 'true' }}
      working-directory: ${{ inputs.workdir }}
      run: |
        content=$(base64 -i "${{ inputs.file }}")
        url=https://api.github.com/repos/${{ inputs.repo }}/contents/${{ inputs.file }}
        sha=$(git rev-parse "${{ inputs.branch }}:${{ inputs.file }}")
        message=$(printf "%s\n\n%s" "${{ inputs.message }}" \
          "Signed-off-by: github-actions[bot] <support@github.com>")
        json=$(jq -n \
          --arg jowner "$(dirname ${{ inputs.repo }})" \
          --arg jrepo "$(basename ${{ inputs.repo }})" \
          --arg jpath "${{ inputs.file }}" \
          --arg jmessage "$message" \
          --arg jcontent "$content" \
          --arg jsha "$sha" \
          --arg jbranch "${{ inputs.branch }}" \
          '{
            owner: $jowner,
            repo: $jrepo,
            path: $jpath,
            message: $jmessage,
            content: $jcontent,
            sha: $jsha,
            branch: $jbranch
          }'
        )

        curl --retry 5 --retry-max-time 60 --retry-all-errors --fail-with-body \
          -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ inputs.repo }}/contents/${{ inputs.file }}" \
          -d "$json"
      shell: bash
