name: Initialize Workspace
description: Cleanup runner and checkout project code

inputs:
  fetch-depth:
    default: '0'
  ref:
    default: ''
  submodules:
    default: 'recursive'
  token:
    default: ${{ github.token }}
  remote-actions-repo:
    default: ''
  dot-github-only:
    default: 'false'

outputs:
  remote-branch:
    value: ${{ steps.get-remote-branch.outputs.branch }}

runs:
  using: composite
  steps:
    - name: Cleanup previous jobs
      run: |
        echo "Cleaning up previous runs"
        sudo rm -rf ${{ github.workspace }}/*
        sudo rm -rf ${{ github.workspace }}/.??*
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.submodules }}
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        sparse-checkout: ${{ (inputs.dot-github-only == 'true' && '.github') || '' }}

    - name: Determince remote actions branch
      id: get-remote-branch
      if: ${{ inputs.remote-actions-repo != github.repository }}
      run: |
        for b in "${{ github.head_ref || github.ref_name }}" main master; do
          ls_remote="$(git ls-remote --heads \
            "https://github.com/${{ inputs.remote-actions-repo }}" refs/heads/"$b")"
          if [ -n "${ls_remote}" ]; then
            echo "branch=$b" >> "$GITHUB_OUTPUT"
            break
          fi
        done
        echo "Remote actions branch is '$b'"
      shell: bash

    - name: Checkout remote actions repo
      if: ${{ inputs.remote-actions-repo != github.repository }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.remote-actions-repo }}
        ref: ${{ steps.get-remote-branch.outputs.branch }}
        sparse-checkout: '.github'
        path: '.github/remote-actions-repo/'

    - name: Copy remote actions (without overwriting local ones)
      if: ${{ inputs.remote-actions-repo != github.repository }}
      run: |
        cp -rn .github/remote-actions-repo/.github ./
        rm -rf .github/remote-actions-repo
      shell: bash
