name: Readd Issue Label
description: Remove and readd issue label

inputs:
  issue-number:
    required: true
  label:
    required: true
  repo:
    default: ${{ github.repository }}
  token:
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - run: sleep 3
      shell: bash

    - name: Check if label exists
      id: check-label-exists
      run: |
        resp=$(curl --retry 5 --retry-max-time 60 --retry-all-errors \
          -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ inputs.repo }}/issues/${{ inputs.issue-number }}/labels")

        has_error=$(echo "$resp" | \
          jq -c 'if type!="array" then has("status") else . end')
        if [ "${has_error}" == true ]; then
          echo "$(echo "$resp" | jq -r '.message') " \
            "($(echo "$resp" | jq -r '.status'))"
          exit 1
        fi

        ok_to_test=$(echo "$resp" | \
          jq -c ".[] | select(.url | contains(\"${{ inputs.label }}\"))")
        if [ -n "${ok_to_test}" ]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Remove label
      if: ${{ steps.check-label-exists.outputs.exists == 'true' }}
      run: |
        curl --retry 5 --retry-max-time 60 --retry-all-errors --fail-with-body \
          -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ inputs.repo }}/issues/${{ inputs.issue-number }}/labels/${{ inputs.label }}"
      shell: bash

    - name: Readd label
      run: |
        curl --retry 5 --retry-max-time 60 --retry-all-errors --fail-with-body \
          -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ inputs.repo }}/issues/${{ inputs.issue-number }}/labels" \
          -d "$(jq -n --arg l "${{ inputs.label }}" '{ labels: [$l] }')"
      shell: bash
