name: Download from s3
description: Download artifacts from s3

inputs:
  branch:
    default: 'main'
  arch:
    default: 'x86_64'
  build-type:
    default: 'release'
  local-path:
    default: '.'
  remote-basepath:
    default: 'nbfc-assets/github/vaccel'
  remote-subpath:
    default: ''
  remote-files:
    default: '*latest*'
  access-key:
    required: true
  secret-key:
    required: true
  install:
    default: 'false'

outputs:
  installed:
    value: ${{ steps.install.outputs.installed }}

runs:
  using: composite
  steps:
    - name: Generate paths and verify output dir exists
      id: get-artifact-vars
      run: |
        mkdir -p "${{ inputs.local-path }}"
        local_path=$(realpath -s --relative-to="${{ github.workspace }}" \
          "${{ inputs.local-path }}")
        echo "local-path=${local_path}/" >> "$GITHUB_OUTPUT"
        base_path="${{ inputs.remote-basepath }}"
        if [ -n "${{ inputs.remote-subpath }}" ]; then
          base_path="${base_path}/${{ inputs.remote-subpath }}"
        fi
        remote_path="${base_path}/rev/${{inputs.branch}}/${{inputs.arch}}/${{inputs.build-type}}"
        remote_path="${remote_path}/${{ inputs.remote-files }}"
        echo "remote-path=${remote_path}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Download artifacts from s3
      uses: cloudkernels/minio-download@v5
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ inputs.access-key }}
        secret-key: ${{ inputs.secret-key }}
        local-path: ${{ steps.get-artifact-vars.outputs.local-path }}
        remote-path: ${{ steps.get-artifact-vars.outputs.remote-path }}

    - name: Install deb artifacts
      id: install
      working-directory: ${{ inputs.local-path }}
      if: ${{ inputs.install == 'true' }} 
      run: |
        for d in $(ls -1 *.deb); do
          sudo dpkg -i "$d" || continue
          installed+=" $(dpkg -f "$d" 'Package')"
        done
        echo "installed=${installed}" >> "$GITHUB_OUTPUT"
      shell: bash
