name: 'Run Examples'
description: 'Run project examples'

inputs:
  prefix:
    description: 'Installation prefix'
    default: ${{ github.workspace }}/opt
  valgrind:
    description: 'Whether to run the examples with valgrind'
    default: 'false'
  package:
    description: 'Name of the package with the examples'
    default: 'vaccel'

runs:
  using: 'composite'
  steps:
    - name: Ensure run dir exists
      run: |
        uid=$(id -u)
        run_dir="/run/user/${uid}"

        if [[ -d "$run_dir" ]]; then
          exit 0
        fi

        sudo mkdir -p "$run_dir"
        sudo chown -R  "$uid" "$run_dir"
      shell: bash

    - name: Run examples
      env:
        PACKAGE: ${{ inputs.package }}
        VALGRIND: ${{ inputs.valgrind }}
        PREFIX: ${{ inputs.prefix }}
      run: |
        if [[ "$PACKAGE" == 'vaccel' ]]; then
          package_name="$PACKAGE"
        else
          package_name="vaccel-${PACKAGE}"
        fi

        if [[ "$VALGRIND" == 'true' ]]; then
          use_valgrind=1
        else
          use_valgrind=0
        fi

        export PKG_CONFIG_PATH=$(find "$PREFIX" \
          -type d -name "pkgconfig" | head -1)
        "$GITHUB_WORKSPACE"/scripts/run-examples.sh \
          "$package_name" "$use_valgrind"
      shell: bash
