name: Run Examples
description: Run vaccel examples

inputs:
  prefix:
    default: ${{ github.workspace }}/opt
  valgrind:
    default: 'false'
  package:
    default: 'vaccel'

runs:
  using: composite
  steps:
    - name: Ensure run dir exists
      run: |
        uid=$(id -u)
        [ -d "/run/user/${uid}" ] && exit 0
        sudo mkdir -p "/run/user/${uid}"
        sudo chown -R  "${uid}" "/run/user/${uid}"
      shell: bash

    - name: Run examples
      run: |
        if [ "${{ inputs.package }}" == "vaccel" ]; then
          "${{ github.workspace }}"/scripts/run-examples.sh \
            "${{ inputs.prefix }}" "${{ inputs.valgrind }}"
        else
          "${{ github.workspace }}"/scripts/run-examples.sh \
            "${{ inputs.prefix }}" "${{ inputs.valgrind }}" "/usr"
        fi
      shell: bash
