self-hosted-runner:
  labels:
    - '*-*-amd64'
    - '*-dind-*-amd64'
    - '*-*-arm*'
    - '*-dind-*-arm*'

paths:
  .github/**/*.{yml,yaml}:
    ignore:
      # Workaround rules for https://github.com/rhysd/actionlint/issues/648
      - 'missing input "app-id" which is required by action "actions/create-github-app-token@v3".+'
      - 'input "client-id" is not defined in action "actions/create-github-app-token@v3".+'
