name: 'Upload to s3'
description: 'Upload artifacts to s3'

inputs:
  arch:
    description: 'OS architecture of the artifacts'
    default: 'x86_64'
  build-type:
    description: 'Build type of the artifacts'
    default: 'release'
  local-path:
    description: 'Local path where the artifacts are'
    default: 'build'
  remote-basepath:
    description: 'Remote base path (relative to the root)'
    default: 'nbfc-assets/github/vaccel'
  remote-subpath:
    description: 'Remote subpath for artifacts (relative to the base path)'
    default: ''
  access-key:
    description: 'Access key for S3 authentication'
    required: true
  secret-key:
    description: 'Secret access key for S3 authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Determine SHA and branch
      id: get-revision
      uses: ./.github/actions/get-revision-info

    - name: Generate paths
      id: get-artifact-vars
      env:
        LOCAL_PATH: ${{ inputs.local-path }}
        BASE_PATH: ${{ inputs.remote-basepath }}
        SUBPATH: ${{ inputs.remote-subpath }}
        REF: ${{ steps.get-revision.outputs.ref }}
        ARCH: ${{ inputs.arch }}
        BUILD_TYPE: ${{ inputs.build-type }}
      run: |
        local_path=$(realpath -s --relative-to="$GITHUB_WORKSPACE" \
          "$LOCAL_PATH")

        base_path="$BASE_PATH"
        if [[ -n "$SUBPATH" ]]; then
          base_path="${base_path}/${SUBPATH}"
        fi
        remote_path="${base_path}/rev/${REF}/${ARCH}/${BUILD_TYPE}"

        {
          echo "local-path=${local_path}/"
          echo "remote-path=${remote_path}"
        } >> "$GITHUB_OUTPUT"
        echo "Local path: ${local_path}"
        echo "Remote path: ${remote_path}"
      shell: bash

    - name: Generate latest artifacts
      uses: ./.github/actions/generate-latest-artifacts
      with:
        local-path: ${{ inputs.local-path }}

    - name: Upload artifacts to s3
      uses: cloudkernels/minio-upload@v5
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ inputs.access-key }}
        secret-key: ${{ inputs.secret-key }}
        local-path: ${{ steps.get-artifact-vars.outputs.local-path }}
        remote-path: ${{ steps.get-artifact-vars.outputs.remote-path }}
        policy: 1
