name: Upload to s3
description: Upload artifacts to s3

inputs:
  arch:
    default: 'x86_64'
  build-type:
    default: 'release'
  local-path:
    default: 'build'
  remote-basepath:
    default: 'nbfc-assets/github/vaccel'
  remote-subpath:
    default: ''
  access-key:
    required: true
  secret-key:
    required: true

runs:
  using: composite
  steps:
    - name: Determine SHA, branch and remote paths
      id: get-artifact-vars
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          if [ "${{ github.event.pull_request.merged }}" == true ]; then
            sha="${{ github.sha }}"
            branch="${{ github.base_ref }}"
            echo "PR merged. SHA: $sha, Branch: $branch"
          else
            sha="${{ github.event.pull_request.head.sha }}"
            branch="${{ github.event.pull_request.head.ref }}"
            echo "PR not yet merged. SHA: $sha, Branch: $branch"
          fi
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          sha="${{ github.sha }}"
          branch="${{ github.event.ref_name }}"
          echo "Workflow dispatch event. SHA: $sha, Branch: $branch"
        else
          echo "Event not supported."
          exit 1
        fi
        local_path=$(realpath -s --relative-to="${{ github.workspace }}" \
          "${{ inputs.local-path }}")
        echo "local-path=${local_path}" >> "$GITHUB_OUTPUT"
        base_path="${{ inputs.remote-basepath }}"
        if [ -n "${{ inputs.remote-subpath }}" ]; then
          base_path="${base_path}/${{ inputs.remote-subpath }}"
        fi
        remote_path="${base_path}/rev/${branch}/${{inputs.arch}}/${{inputs.build-type}}/"
        echo "remote-path=${remote_path}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Generate \"latest\" artifacts
      run: |
        if [ -d "${{ inputs.local-path }}" ]; then
          echo "Local path is a directory, skipping"
          exit 0
        fi
        # attempt to match filenames of the form
        # pkg-A.B.C[-D-E{8}-][-M][moretext].extension
        # where capital letters are numbers and E is 8 digits long
        VERSION_REGEX="(.+)\d+\.\d+\.\d+(-\d+-[\da-z].{7})*(-\d+)*([^.]*\..+)"
        pushd "$(dirname "${{ inputs.local-path }}")"
        for f in $(ls -d *); do
          [ ! -f "$f" ] && continue
          latest_filename=$(echo "$f" | \
            perl -pe "s/${VERSION_REGEX}/\1latest\4/g")
          echo "Copying $f to ${latest_filename}"
          cp "$f" "${latest_filename}"
        done
        popd
      shell: bash

    - name: Upload artifact to s3
      uses: cloudkernels/minio-upload@v4
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ inputs.access-key }}
        secret-key: ${{ inputs.secret-key }}
        local-path: ${{ steps.get-artifact-vars.outputs.local-path }}
        remote-path: ${{ steps.get-artifact-vars.outputs.remote-path }}
        policy: 1
