// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "include/vaccel/config.h" // IWYU pragma: export
#include <stdbool.h>
#include <stddef.h>

#define CONFIG_LOG_LEVEL_DEFAULT VACCEL_LOG_ERROR
#define CONFIG_LOG_FILE_DEFAULT NULL
#define CONFIG_PLUGINS_DEFAULT NULL
#define CONFIG_PROFILING_ENABLED_DEFAULT false
#define CONFIG_VERSION_IGNORE_DEFAULT false

#define CONFIG_LOG_LEVEL_ENV "VACCEL_LOG_LEVEL"
#define CONFIG_LOG_LEVEL_OLD_ENV "VACCEL_DEBUG_LEVEL"
#define CONFIG_LOG_FILE_ENV "VACCEL_LOG_FILE"
#define CONFIG_PLUGINS_ENV "VACCEL_PLUGINS"
#define CONFIG_PLUGINS_OLD_ENV "VACCEL_BACKENDS"
#define CONFIG_PROFILING_ENABLED_ENV "VACCEL_PROFILING_ENABLED"
#define CONFIG_VERSION_IGNORE_ENV "VACCEL_VERSION_IGNORE"
#define CONFIG_VERSION_IGNORE_OLD_ENV "VACCEL_IGNORE_VERSION"
