name: Check PR is merged

on:
  workflow_call:
    inputs:
      actions-repo:
        type: string
        default: 'nubificus/vaccel'
      actions-rev:
        type: string
        default: 'main'
    outputs:
      is-merged:
        value: ${{ jobs.check-merged.outputs.is-merged }}
    secrets:
      GIT_CLONE_PAT:
        required: false

jobs:
  check-merged:
    name: Check PR is merged
    runs-on: [gcc-2204-amd64]
    outputs:
      is-merged: ${{ steps.check.outputs.is-merged }}
    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          repository: ${{ inputs.actions-repo }}
          ref: ${{ inputs.actions-rev }}

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace
        with:
          fetch-depth: 0
          remote-actions-repo: ${{ inputs.actions-repo }}
          token: ${{ secrets.GIT_CLONE_PAT || github.token }}

      - name: Check merged
        id: check
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ] || \
            [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "The PR was merged - running upload workflows"
            echo "is-merged=true" >> "$GITHUB_OUTPUT"
          else
            echo "The PR is not merged. Exiting..."
            echo "is-merged=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
