name: Coverage Report

on:
  workflow_call:
    inputs:
      actions-repo:
        description: 'Repository with remote actions'
        type: string
        default: 'nubificus/vaccel'
      actions-ref:
        description: 'Branch, tag or SHA of remote actions repository'
        type: string
        default: 'main'
      options:
        description: 'Comma-separated list of build options'
        type: string
        default: 'auto_features=enabled'
      commit:
        description: 'Whether to commit the coverage report'
        type: boolean
        default: false
      comment-diff:
        description: >
          Whether to post a pull request comment with the coverage diff
        type: boolean
        default: false
    secrets:
      VACCEL_BOT_PRIVATE_KEY:
        required: false
      AWS_ACCESS_KEY:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

permissions: read-all

env:
  ACTIONS_REF: >-
    ${{ github.repository != inputs.actions-repo && inputs.actions-ref || '' }}

jobs:
  coverage-report:
    name: Coverage Report
    runs-on: base-dind-2204-amd64
    strategy:
      matrix:
        build-type: [plain]
      fail-fast: false
    env:
      DOWNLOAD_PATH: >-
        ${{ format('{0}/artifacts/downloads/{1}', github.workspace,
          matrix.build-type) }}
    steps:
      - name: Set repository directories
        id: set-repo-dirs
        env:
          DEFAULT_BRANCH: >-
            ${{ github.event.repository.default_branch || 'main' }}
        run: |
          repo_name="$(basename "$GITHUB_REPOSITORY")"
          {
            echo "repo=${repo_name}"
            echo "repo-default=${repo_name}_${DEFAULT_BRANCH}"
          }  >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Generate initialization vaccel-bot token
        id: generate-init-token
        if: vars.VACCEL_BOT_CLIENT_ID
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.VACCEL_BOT_CLIENT_ID }}
          private-key: ${{ secrets.VACCEL_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-contents: read

      - name: Checkout .github directory
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github
          repository: ${{ inputs.actions-repo }}
          ref: ${{ env.ACTIONS_REF }}
          token: ${{ steps.generate-init-token.outputs.token || github.token }}

      - name: Initialize workspace
        id: initialize-workspace
        uses: ./.github/actions/initialize-workspace
        with:
          remote-actions-repo: ${{ inputs.actions-repo }}
          dot-github-only: 'true'
          token: ${{ steps.generate-init-token.outputs.token || github.token }}

      - name: Download artifacts from s3
        id: download-artifacts
        if: inputs.actions-repo != github.repository
        uses: ./.github/actions/download-from-s3
        with:
          ref: >-
            ${{ steps.initialize-workspace.outputs.remote-tag ||
              steps.initialize-workspace.outputs.remote-branch }}
          build-type: ${{ matrix.build-type }}
          access-key: ${{ secrets.AWS_ACCESS_KEY }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          local-path: ${{ env.DOWNLOAD_PATH }}
          install: 'true'

      - name: Checkout current branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          path: ${{ steps.set-repo-dirs.outputs.repo }}

      - name: Build project
        uses: ./.github/actions/build
        with:
          build-path: build_${{ matrix.build-type }}
          build-type: ${{ matrix.build-type }}
          source-path: ${{ steps.set-repo-dirs.outputs.repo }}
          coverage: 'true'
          options: ${{ inputs.options }}

      - name: Generate coverage report
        uses: ./.github/actions/run-tests
        with:
          build-path: build_${{ matrix.build-type }}
          source-path: ${{ steps.set-repo-dirs.outputs.repo }}
          coverage: 'true'

      - name: Checkout default_branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          path:  ${{ steps.set-repo-dirs.outputs.repo-default }}

      - name: Build project @default_branch
        if: inputs.comment-diff == true
        uses: ./.github/actions/build
        with:
          build-path: build_${{ matrix.build-type }}
          build-type: ${{ matrix.build-type }}
          source-path: ${{ steps.set-repo-dirs.outputs.repo-default }}
          coverage: 'true'
          options: ${{ inputs.options }}

      - name: Generate coverage report @default_branch
        if: inputs.comment-diff == true
        uses: ./.github/actions/run-tests
        with:
          build-path: build_${{ matrix.build-type }}
          source-path: ${{ steps.set-repo-dirs.outputs.repo-default }}
          coverage: 'true'

      - name: Calculate coverage diff
        if: inputs.comment-diff == true
        env:
          REPO_DEFAULT_DIR: ${{ steps.set-repo-dirs.outputs.repo-default }}
          REPO_DIR: ${{ steps.set-repo-dirs.outputs.repo }}
          BUILD_TYPE: ${{ matrix.build-type }}
        run: |
          pycobertura diff \
            "$(find "${REPO_DEFAULT_DIR}/build_${BUILD_TYPE}" \
              -name "coverage*.xml")" \
            "$(find "${REPO_DIR}/build_${BUILD_TYPE}" -name "coverage*.xml")" \
            --no-color --no-source -f markdown > coverage_diff.txt ||
            PYCOB_RESULT="$?"

          echo "pycobertura exited with ${PYCOB_RESULT:-0}"
          if [[ "$PYCOB_RESULT" == 1 ]]; then
            exit 1
          fi

          echo -e '# Coverage report diff\n' > coverage_diff.md && \
            cat coverage_diff.txt >> coverage_diff.md
        shell: bash

      - name: Generate PR vaccel-bot token
        id: generate-pr-token
        if: >-
          vars.VACCEL_BOT_CLIENT_ID &&
          (inputs.comment-diff == true || inputs.commit == true)
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.VACCEL_BOT_CLIENT_ID }}
          private-key: ${{ secrets.VACCEL_BOT_PRIVATE_KEY }}
          permission-contents: >-
            ${{ inputs.commit == true && 'write' || 'read' }}
          permission-pull-requests: write

      - name: PR comment with file
        if: inputs.comment-diff == true
        uses: mshick/add-pr-comment@v3
        with:
          message-path: ./coverage_diff.md
          message-id: 'coverage'
          repo-token: >-
            ${{ steps.generate-pr-token.outputs.token || github.token }}

      - name: Generate markdown file
        id: generate-md-file
        if: inputs.commit == true
        env:
          REPO_DIR: ${{ steps.set-repo-dirs.outputs.repo }}
          BUILD_TYPE: ${{ matrix.build-type }}
          COVERAGE_FILE: 'docs/tests/coverage/coverage.md'
        run: |
          pycobertura show \
            "$(find "${REPO_DIR}/build_${BUILD_TYPE}" -name "coverage*.xml")" \
            --format markdown \
            --output "coverage.md"

          printf "%s\n%s\n\n" \
            '<!-- markdownlint-disable-file MD013 -->' \
            '# Tests coverage report' \
            > "${REPO_DIR}/$COVERAGE_FILE"
          cat coverage.md >> "${REPO_DIR}/${COVERAGE_FILE}"
          rm -f coverage.md
          echo "coverage-file=${COVERAGE_FILE}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Commit report
        if: inputs.commit == true
        uses: ./.github/actions/commit-file
        with:
          workdir: ${{ steps.set-repo-dirs.outputs.repo }} 
          branch: ${{ github.event.pull_request.head.ref || github.ref_name }} 
          file: ${{ steps.generate-md-file.outputs.coverage-file }}
          message: "docs(coverage): Update coverage report"
          token: ${{ steps.generate-pr-token.outputs.token || github.token }}

      - name: Clean-up
        if: always()
        env:
          REPO_DIR: ${{ steps.set-repo-dirs.outputs.repo }}
          REPO_DEFAULT_DIR: ${{ steps.set-repo-dirs.outputs.repo-default }}
          INSTALLED: ${{ steps.download-artifacts.outputs.installed }}
        run: |
          sudo rm -rf artifacts coverage* "$REPO_DIR" "$REPO_DEFAULT_DIR"
          sudo apt-get purge -y "$INSTALLED" || true
        shell: bash
