name: Prepare Release
run-name: >-
  ${{ format('Prepare release · {0} ({1})',
    inputs.component || github.event.repository.name, inputs.version) }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.3.2+core-0.7.0)'
        type: string
        required: true
      component:
        description: >
          Component to release. Defaults to the current repository name.
        type: string
        required: false
      branch:
        description: 'Branch to release'
        type: string
        required: false
      core-component:
        description: 'Core component name'
        type: string
        required: true
      core-version:
        description: 'Core component version'
        type: string
        required: true
      tracking-issue-url:
        description: 'Tracking issue URL'
        type: string
        required: true
      orchestrator-repo:
        description: 'Repository orchestrating the release (e.g., owner/repo)'
        type: string
        required: true
      dependencies:
        description: >
          JSON array of dependencies to update, e.g.,
          [{"name": "dep1", "version": "0.2.0"}]
        type: string
        required: true

concurrency:
  group: >-
    ${{ format('{0}-{1}_{2}',
      github.workflow, inputs.component || github.repository, inputs.version) }}

permissions: read-all

jobs:
  prepare-release:
    name: Prepare Release (Generic)
    uses: ./.github/workflows/prepare-release.yml
    with:
      version: ${{ inputs.version }}
      component: ${{ inputs.component }}
      branch: ${{ inputs.branch }}
      core-component: ${{ inputs.core-component }}
      core-version: ${{ inputs.core-version }}
      tracking-issue-url: ${{ inputs.tracking-issue-url }}
      orchestrator-repo: ${{ inputs.orchestrator-repo }}
      dependencies: ${{ inputs.dependencies }}
    secrets: inherit
