name: Build and Upload

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: read-all

jobs:
  build-dist:
    name: Build and Upload
    uses: ./.github/workflows/verify-build.yml
    with:
      release: true
    secrets: inherit

  update-release:
    needs: build-dist
    name: Update Release
    if: always()
    uses: ./.github/workflows/update-release.yml
    with:
      create-github-release: false
      result: ${{ needs.build-dist.result }}
    secrets: inherit
