name: Build and Upload

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-merged:
    name: Check PR is merged
    uses: ./.github/workflows/check-merged.yml
    secrets: inherit

  build-dist:
    needs: [check-merged]
    name: Build and Upload
    if: ${{ needs.check-merged.outputs.is-merged == 'true' }}
    uses: ./.github/workflows/verify-build.yml
    with:
      release: true
    secrets: inherit
