name: Build and Verify

on:
  pull_request:
    branches: ["main"]
    types: [synchronize, labeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    name: Test Build
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/test-build.yml
    secrets: inherit

  verify-build:
    name: Verify Build
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/verify-build.yml
    secrets: inherit

  validate-files-and-commits:
    name: Validate Files and Commits
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/validate-files-and-commits.yml
    secrets: inherit

  validate-code:
    name: Validate Code
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/validate-code.yml
    secrets: inherit

  generate-coverage:
    needs: [test-build, verify-build, validate-files-and-commits, validate-code]
    name: Generate Coverage Report
    uses: ./.github/workflows/coverage-report.yml
    with:
      comment-diff: true
