# SPDX-License-Identifier: Apache-2.0

name: Add Git Trailers to PR commits

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize, labeled]

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

permissions: read-all

jobs:
  check-pr-status:
    name: Check PR status
    if: github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/check-pr-status.yml
    with:
      pr-number: >-
        ${{ github.event.pull_request_review.pull_request.number ||
          github.event.pull_request.number }}
    secrets: inherit

  add-git-trailers:
    needs: check-pr-status
    name: Add Git Trailers to PR commits
    if: >-
      always() &&
      github.event.pull_request.base.ref == 'main' &&
      needs.check-pr-status.outputs.is-approved == 'true'
    uses: ./.github/workflows/add-git-trailers.yml
    secrets: inherit
