# SPDX-License-Identifier: Apache-2.0

name: Test Build

on:
  workflow_call:
    inputs:
      actions-repo:
        description: 'Repository with remote actions'
        type: string
        default: 'nubificus/vaccel'
      actions-ref:
        description: 'Branch, tag or SHA of remote actions repository'
        type: string
        default: 'main'
      runner:
        description: 'JSON array of runner name parts (excluding architecture)'
        type: string
        default: '["base", "2204"]'
      runner-archs:
        description: 'JSON array of runner architectures to run on'
        type: string
        default: '["amd64", "arm64", "arm"]'
      runner-arch-map:
        description: 'JSON object mapping runner to GNU architectures'
        type: string
        default: '[{"amd64":"x86_64", "arm64":"aarch64", "arm":"armv7l"}]'
      options:
        description: 'Comma-separated list of build options'
        type: string
        default: 'auto_features=enabled'
      valgrind:
        description: 'Whether to run the tests with valgrind'
        type: boolean
        default: true
    secrets:
      VACCEL_BOT_PRIVATE_KEY:
        required: false
      AWS_ACCESS_KEY:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

permissions: read-all

env:
  ACTIONS_REF: >-
    ${{ github.repository != inputs.actions-repo && inputs.actions-ref || '' }}

jobs:
  test-build:
    name: Test Build
    runs-on: ${{ format('{0}-{1}', join(fromJSON(inputs.runner), '-'), matrix.arch) }}
    strategy:
      matrix:
        arch: ["${{ fromJSON(inputs.runner-archs) }}"]
        build-type: [debug, release]
      fail-fast: false
    env:
      ARCH: ${{ fromJson(inputs.runner-arch-map)[0][matrix.arch] }}
      DOWNLOAD_PATH: >-
        ${{ format('{0}/artifacts/downloads/{1}/{2}', github.workspace,
          fromJson(inputs.runner-arch-map)[0][matrix.arch], matrix.build-type) }}
    steps:
      - name: Generate vaccel-bot token
        id: generate-token
        if: vars.VACCEL_BOT_CLIENT_ID
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.VACCEL_BOT_CLIENT_ID }}
          private-key: ${{ secrets.VACCEL_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-contents: read

      - name: Checkout .github directory
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github
          repository: ${{ inputs.actions-repo }}
          ref: ${{ env.ACTIONS_REF }}
          token: ${{ steps.generate-token.outputs.token || github.token }}

      - name: Initialize workspace
        id: initialize-workspace
        uses: ./.github/actions/initialize-workspace
        with:
          fetch-depth: 0
          remote-actions-repo: ${{ inputs.actions-repo }}
          token: ${{ steps.generate-token.outputs.token || github.token }}

      - name: Download artifacts from s3
        id: download-artifacts
        if: inputs.actions-repo != github.repository
        uses: ./.github/actions/download-from-s3
        with:
          ref: >-
            ${{ steps.initialize-workspace.outputs.remote-tag ||
              steps.initialize-workspace.outputs.remote-branch }}
          build-type: ${{ matrix.build-type }}
          arch: ${{ env.ARCH }}
          access-key: ${{ secrets.AWS_ACCESS_KEY }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          local-path: ${{ env.DOWNLOAD_PATH }}
          install: 'true'

      - name: Build project
        uses: ./.github/actions/build
        with:
          build-path: build_${{ matrix.build-type }}
          build-type: ${{ matrix.build-type }}
          options: ${{ inputs.options }}

      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          valgrind: ${{ inputs.valgrind }}
          build-path: build_${{ matrix.build-type }}

      - name: Clean-up
        if: always()
        env:
          INSTALLED: ${{ steps.download-artifacts.outputs.installed }}
        run: |
          sudo rm -rf artifacts build*
          sudo apt-get purge -y "$INSTALLED" || true
        shell: bash
