name: Test Build

on:
  workflow_call:
    inputs:
      actions-repo:
        type: string
        default: 'nubificus/vaccel'
      actions-rev:
        type: string
        default: 'main'
      runner:
        type: string
        default: '["gcc", "2204"]'
      runner-archs:
        type: string
        default: '["amd64", "arm64", "arm"]'
      runner-arch-map:
        type: string
        default: '[{"amd64":"x86_64", "arm64":"aarch64", "arm":"armv7l"}]'
      options:
        type: string
        default: 'auto_features=enabled'
      valgrind:
        type: boolean
        default: true
    secrets:
      GIT_CLONE_PAT:
        required: false
      AWS_ACCESS_KEY:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

env:
  ACTIONS_REV: ${{ (github.repository != inputs.actions-repo) && inputs.actions-rev || '' }}

jobs:
  test-build:
    name: Test Build
    runs-on: ${{ format('{0}-{1}', join(fromJSON(inputs.runner), '-'), matrix.arch) }}
    strategy:
      matrix:
        arch: ["${{ fromJSON(inputs.runner-archs) }}"]
        build-type: [debug, release]
      fail-fast: false
    env:
      ARCH: ${{ fromJson(inputs.runner-arch-map)[0][matrix.arch] }}
      DOWNLOAD_PATH: ${{github.workspace}}/artifacts/downloads/${{fromJson(inputs.runner-arch-map)[0][matrix.arch]}}/${{matrix.build-type}}
    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          repository: ${{ inputs.actions-repo }}
          ref: ${{ env.ACTIONS_REV }}

      - name: Initialize workspace
        id: initialize-workspace
        uses: ./.github/actions/initialize-workspace
        with:
          fetch-depth: 0
          remote-actions-repo: ${{ inputs.actions-repo }}
          token: ${{ secrets.GIT_CLONE_PAT || github.token }}

      # FIXME: Temp
      - name: Install libcurl & stb
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libstb-dev
        shell: bash

      - name: Download artifacts from s3
        id: download-artifacts
        if: ${{ inputs.actions-repo != github.repository }}
        uses: ./.github/actions/download-from-s3
        with:
          branch: ${{ steps.initialize-workspace.outputs.remote-branch }}
          build-type: ${{ matrix.build-type }}
          arch: ${{ env.ARCH }}
          access-key: ${{ secrets.AWS_ACCESS_KEY }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          local-path: ${{ env.DOWNLOAD_PATH }}
          install: 'true'

      - name: Build project
        uses: ./.github/actions/build
        with:
          build-path: build_${{ matrix.build-type }}
          build-type: ${{ matrix.build-type }}
          options: ${{ inputs.options }}

      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          valgrind: ${{ inputs.valgrind }}
          build-path: build_${{ matrix.build-type }}

      - name: Clean-up
        if: ${{ always() }}
        run: |
          sudo rm -rf artifacts build*
          sudo apt-get purge -y \
            ${{ steps.download-artifacts.outputs.installed }} || echo
        shell: bash
