name: Validate Files and Commit Messages

on:
  workflow_call:
    inputs:
      actions-repo:
        type: string
        default: 'nubificus/vaccel'
      actions-rev:
        type: string
        default: 'main'
    secrets:
      GIT_CLONE_PAT:
        required: false

jobs:
  linter-commitlint:
    name: Lint Commit Messages
    runs-on: [gcc-dind-2204-amd64]
    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          repository: ${{ inputs.actions-repo }}
          ref: ${{ inputs.actions-rev }}

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace
        with:
          submodules: 'false'
          remote-actions-repo: ${{ inputs.actions-repo }}
          token: ${{ secrets.GIT_CLONE_PAT || github.token }}

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .github/linters/commitlint.config.mjs

  linter-typos:
    name: Spell Check Repo
    runs-on: [gcc-dind-2204-amd64]
    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          repository: ${{ inputs.actions-repo }}
          ref: ${{ inputs.actions-rev }}

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace
        with:
          submodules: 'false'
          remote-actions-repo: ${{ inputs.actions-repo }}
          token: ${{ secrets.GIT_CLONE_PAT || github.token }}

      - name: Spell check
        uses: crate-ci/typos@master
        with:
          config: .github/linters/typos.toml

  linter-license-eye:
    name: Check License Headers
    runs-on: [gcc-dind-2204-amd64]
    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          repository: ${{ inputs.actions-repo }}
          ref: ${{ inputs.actions-rev }}

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace
        with:
          submodules: 'false'
          remote-actions-repo: ${{ inputs.actions-repo }}
          token: ${{ secrets.GIT_CLONE_PAT || github.token }}

      - name: Run license-eye
        uses: apache/skywalking-eyes/header@main
        with:
          config: .github/linters/licenserc.yml
          token: ${{ secrets.GITHUB_TOKEN }}
